services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs371-backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  db:
    image: mysql:8.0
    container_name: cs371-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./mysql-config:/etc/mysql/conf.d

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: