version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs371-backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: cs371-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    container_name: cs371-migrate
    command: [
      "-database", "mysql://root:${DB_PASSWORD}@tcp(cs371-db:${DB_PORT})/${DB_NAME}?multiStatements=true",
      "-path", "/migrations",
      "up"
    ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
