### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create Course
POST http://localhost:8080/api1/courses
Content-Type: application/json

{
  "class_id": "f8faf4f0-09cb-11f0-9cd2-0242ac120002",
  "title": "Math",
  "description": "Mathematics",
  "difficulty_level": "medium",
  "number" : 1
}

### Get Courses by Class ID
GET http://localhost:8080/api1/courses/class/0195ca5b-dcf4-7a75-948b-5b27d9a57eef

### Update Course
PUT http://localhost:8080/api1/courses/cb8c2a86-de34-4f00-8541-99c4db43bcaf
Content-Type: application/json

{
  "title": "Mathematics",
  "description": "Mathematics",
  "difficulty_level": "medium",
  "number" : 1
}

### Delete Course
DELETE http://localhost:8080/api1/courses/cb8c2a86-de34-4f00-8541-99c4db43bcaf

###