### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Register User
POST http://localhost:8080/api1/users
Content-Type: application/json

{
    "username": "user3",
    "password": "password1",
    "email": "test3@gmail.com",
    "first_name": "John",
    "last_name": "Doe",
    "role": "student"
}

###